version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "bash", "-c", "rpk clsuter info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
  
  # timescaledb:

  ingestion:
    build: ../services/ingestion
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ../services/ingestion/app
          target: /app/app
    # volumes:
    #   - ../services/ingestion/app:/app/app

  # processor:

  dashboard:
    build: ../services/dashboard
    ports:
      - "3000:3000"
    # develop:
    #   watch:
    #     - action: sync
    #       path: ../services/dashboard/app/src
    #       target: /app/src
    volumes:
      - ../services/dashboard/app/src:/app/src
      - /app/node_modules

